### ISSUE TITLE
Continuous deployment

### ISSUE THREAD

**Issue by rjackson** [tfwiki/deployment#11]
One of the strengths of Kubernetes is it removes the need for human intervention in so many aspects of running a site.

Currently, human intervention is necessary to _deploy_ updates to our Kubernetes environment via `kubectl apply...`.

This isn't great:
* Every developer who works on the Wiki would need direct access to the Kubernetes clusters (not minimising risk)
* I can deploy changes I haven't pushed up to Git yet (violating single-source-of-truth)
* I could accidentally deploy changes for the development environment on the production cluster (error-prone)
* I could fat-finger my keyboard and do something _completely_ unintentional to the cluster (error-prone)

I would much rather have this repository serve as the source-of-truth for the Kubernetes clusters, and have the act of having commits land in here be the trigger for the cluster to update. That would mitigate all of the above concerns.

Useful resources:
* https://github.com/GoogleCloudPlatform/continuous-deployment-on-kubernetes
* https://buddy.works/

**Comment by i-ghost** [comment]
In my opinion, based on experience, set up a cycle like so:

* Have a branch as a source of truth, probably `master`.
* Gate merges into said branches using merge requests. We can discuss/update contents as necessary. If we're feeling adventurous, maybe spin up a cluster based on the branched changes automatically.
* Merge into `master` when ready, which triggers the cluster update.

Buddyworks looks good. Is Valve OK with them, or would they prefer something running within GCP to run CD?

**Comment by rjackson** [comment]
Yeah that's about what I had in mind.

Haven't started properly evaluating any particular service, nor asked Valve's opinion.

Buddy didn't look quite as straight forward to integrate with Kubernetes' as I had hoped (we have to choose deployment scripts manually...  although maybe that's just how things need to be :man_shrugging:). They have turned me right off though by putting together an onboarding email by mining my LinkedIn account for data (skills & employee info). Not a fan of that at all.

**Comment by i-ghost** [comment]
Wow that sucks. circleci is supposed to be quite good but gets pricey real quick. Not sure how Travis' pricing applies when this repo isn't really an open source project as such.

I'd personally advocate just deploying GitLab on GKE, then assign a cluster for build jobs as part of the built in CI/CD. At least that way everything is self-hosted, and it could do automatic deploys on branches before merging. That's a whole other thing though.

**Comment by rjackson** [comment]
Couple of tools I've seen mentioned over the past few months

* https://github.com/GoogleContainerTools/skaffold
* * [Associated discussion on HN](https://news.ycombinator.com/item?id=16538090) mentions many similar tools
* Microsoft Draft
* Gitkube
* knative
